[package]
name = "risc0"
version = "0.3.0"
edition = "2021"
resolver = "2"
license = "MIT OR Apache-2.0"
publish = false

[build-dependencies]
risc0-build = "0.18"

[package.metadata.risc0]
methods = ["guest-sugondat", "guest-mock"]

[features]
bench = []
