[package]
name = "sov-demo-prover-guest-sugondat"
version = "0.3.0"
edition = "2021"
resolver = "2"

[workspace]

[dependencies]
anyhow = "1.0.68"
risc0-zkvm = { version = "0.18", default-features = false, features = ["std"] }
risc0-zkvm-platform = "0.18"
demo-stf = { path = "../../../stf" }
sov-risc0-adapter = { git = "https://github.com/Sovereign-Labs/sovereign-sdk", rev = "6058b31" }
const-rollup-config = { path = "../../../../const-rollup-config" }
sugondat-da-adapter = { path = "../../../../../../adapters/sovereign", default-features = false, features = ["verifier"] }
sov-modules-api = { git = "https://github.com/Sovereign-Labs/sovereign-sdk", rev = "6058b31" }
sov-state = { git = "https://github.com/Sovereign-Labs/sovereign-sdk", rev = "6058b31" }
sov-modules-stf-template = { git = "https://github.com/Sovereign-Labs/sovereign-sdk", rev = "6058b31" }
[patch.crates-io]
sha2 = { git = "https://github.com/risc0/RustCrypto-hashes", rev = "sha2/v0.10.6-risc0" }

[profile.dev]
opt-level = 3

[profile.dev.build-override]
opt-level = 3

[profile.release]
debug = 1
lto = true

[profile.release.build-override]
opt-level = 3

#[features]
#bench = [
#	"sov-celestia-adapter/bench",
#]
